-- AlterEnum
ALTER TYPE "InboxNotificationType" ADD VALUE 'STORAGE_UPGRADE_REJECTED';
ALTER TYPE "InboxNotificationType" ADD VALUE 'PLATFORM_STORAGE_UPGRADE_REQUEST';
ALTER TYPE "InboxNotificationType" ADD VALUE 'CREDITS_WORKSPACE_REVOKE';
